---
# https://pre-commit.com/
# Install pre-commit for your current user:
#   pip3 install --user pre-commit
#
# and then, in the git repo:
#   pre-commit install

repos:
  - repo: https://github.com/jphppd/pre-commit-hooks.git
    rev: 0.0.12
    hooks:
      - id: git-check-mailmap
      - id: git-check
      - id: git-check-added-large-files
      - id: git-check-merge-conflict
      - id: git-commit-msg
      - id: generic-check-byte-order-marker
      - id: generic-check-executables-have-shebangs
      - id: generic-check-symlinks
      - id: generic-check-vcs-permalinks
      - id: generic-detect-private-key
      - id: generic-end-of-file-fixer
      - id: generic-trailing-whitespace
      - id: generic-crlf-forbid
      - id: generic-crlf-remove
      - id: generic-tabs-forbid
      - id: generic-tabs-remove
      - id: generic-nbsp-forbid
      - id: generic-nbsp-remove
      - id: generic-en-dashes-forbid
      - id: generic-en-dashes-remove
      - id: jinja-lint
      - id: json-check-syntax
      - id: json-pretty-format
      - id: python-check-ast
      - id: python-check-builtin-literals
      - id: python-check-docstring-first
      - id: python-debug-statements
      - id: python-double-quote-string-fixer
      - id: python-fix-encoding-pragma
      - id: python-requirements-txt-fixer
      - id: python-pyupgrade
      - id: python-isort-config
      - id: python-isort-seed-config
      - id: python-isort
      - id: python-black
      - id: python-pylint-config
      - id: python-pylint
      - id: python-pydocstyle
      - id: python-setup-cfg-fmt
      - id: rst-linter
      - id: shell-check-syntax
      - id: shell-check
      - id: shell-script-must-have-extension
      - id: shell-script-must-not-have-extension
      - id: shell-bashate
      - id: shell-beautysh
      - id: toml-check-syntax
      - id: xml-check-syntax
      - id: yaml-check-syntax
